AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  step-workshop-m6

  Sample SAM Template for step-workshop-m6
  
Resources:

  
  InputOutputStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: LoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:CreateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                  - logs:GetLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutLogEvents
                  - logs:PutResourcePolicy
                  - logs:UpdateLogDelivery
                Resource: "*"  
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:  
                  - !Join [ ":", [!GetAtt HelloFunction.Arn, "$LATEST"]   ]

 
  
  IOStepFunction:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Logging: 
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt CloudWatchLogsLogGroup.Arn
      Type: EXPRESS
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        HelloFunctionArn: !GetAtt HelloFunction.Arn
      Role: !GetAtt InputOutputStepFunctionRole.Arn
#      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html



  CloudWatchLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 5
      LogGroupName: /aws/stepfunctions/IOStepFunction


  HelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloFunction
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - HelloFunctionRole
          - Arn
      Code:
        ZipFile:
          "exports.handler = (event, context, callback)
          => {\n callback(null, \"Hello, \" + event.who + \"!\");\n};"
      Runtime: nodejs18.x
      Timeout: 300

  HelloFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HelloFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloFunctionRoleArn:
    Description: "Hello Lambda Function ARN"
    Value: !GetAtt HelloFunctionRole.Arn
  HelloFunction:
    Description: "Hello Lambda Function ARN"
    Value: !GetAtt HelloFunction.Arn

  IOStepFunctionArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref IOStepFunction

  InputOutputStepFunctionRoleArn:
    Description: "role for stock trading state machine"
    Value: !GetAtt InputOutputStepFunctionRole.Arn
